### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/yaml-language-server#296]
This is my issue list to work on:

- [x] Include eslint checks in build cycle #278
- [x] Migrate CI to GitHub Actions #295
- [x] Fix all eslint warnings #298
- [x] Auto completion can't suggest string enums correctly in Flow Style content. #239
- [x] Provide completion text to insert without tabs, with only space #283
- [ ] Auto-Edit to turn indent tabs into indent spaces #244
- [ ] Missing textEdit in CompletionItem when there is a newline #288
- [ ] Server returns snippets even though client doesn't support them #161
- [x] uri-reference format validated incorrectly #181
- [ ] Provide full autocompletion when there are multiple requires and only one is fullfilled #46

...
